import { ModuleDefinition } from '../types';

export const SYSTEM_MODULES: ModuleDefinition[] = [
  // Core & Academic
  {
    id: 'mod-students',
    code: 'student_management',
    name: 'Student Information System',
    description: 'Student lifecycle, profiles, academic records, unique institutional identifiers, and cohort progression.',
    category: 'academic',
    is_core: true,
    default_enabled: true,
    icon: 'GraduationCap',
    permissions_provided: ['students.read', 'students.write', 'students.export', 'students.delete'],
  },
  {
    id: 'mod-admissions',
    code: 'admissions',
    name: 'Admissions & Inquiries',
    description: 'Online application workflows, prospective student tracking, intake screening, and conversion into enrolled students.',
    category: 'academic',
    is_core: false,
    default_enabled: true,
    icon: 'UserPlus',
    permissions_provided: ['admissions.manage', 'admissions.review', 'admissions.convert'],
  },
  {
    id: 'mod-academics',
    code: 'academics',
    name: 'Academic Structure & Curriculum',
    description: 'Academic years, terms/semesters, grades/forms, classes/streams, subjects, and curriculum maps.',
    category: 'academic',
    is_core: true,
    default_enabled: true,
    icon: 'BookOpen',
    permissions_provided: ['academics.manage', 'academics.view'],
  },
  {
    id: 'mod-attendance',
    code: 'attendance',
    name: 'Attendance & Truancy Monitoring',
    description: 'Daily and period-level attendance tracking, biometrics integration, automated parent absent alerts, and trends.',
    category: 'academic',
    is_core: false,
    default_enabled: true,
    icon: 'CalendarCheck',
    permissions_provided: ['attendance.mark', 'attendance.view', 'attendance.reports'],
  },
  {
    id: 'mod-examinations',
    code: 'examinations',
    name: 'Examinations & Grading',
    description: 'Exam scheduling, GPA/grade calculation scales, report card generation, transcript printing, and ranking.',
    category: 'academic',
    is_core: false,
    default_enabled: true,
    icon: 'Award',
    permissions_provided: ['exams.create', 'exams.grade', 'exams.publish'],
  },
  {
    id: 'mod-online-exam',
    code: 'online_exam',
    name: 'Online Examination & Quizzes',
    description: 'Computer-based testing (CBT), question banks, timed quizzes, proctoring controls, and automatic scoring.',
    category: 'academic',
    is_core: false,
    default_enabled: false,
    icon: 'Laptop',
    permissions_provided: ['online_exam.author', 'online_exam.attempt', 'online_exam.grade'],
  },
  {
    id: 'mod-timetable',
    code: 'timetable',
    name: 'Timetable & Scheduling',
    description: 'Automated conflict-free class, teacher, room scheduling, rotation cycles, and student timetable views.',
    category: 'academic',
    is_core: false,
    default_enabled: true,
    icon: 'Clock',
    permissions_provided: ['timetable.manage', 'timetable.view'],
  },
  {
    id: 'mod-homework',
    code: 'homework',
    name: 'Homework & Lesson Planning',
    description: 'Assignment distribution, digital submission, teacher lesson plans, syllabus tracking, and feedback loops.',
    category: 'academic',
    is_core: false,
    default_enabled: true,
    icon: 'FileText',
    permissions_provided: ['homework.create', 'homework.submit', 'homework.grade'],
  },

  // Finance & Accounting
  {
    id: 'mod-fees',
    code: 'fees_collection',
    name: 'Fees Collection & Billing',
    description: 'Multi-term fee structures, student ledgers, invoicing, payment receipts, discounts, scholarships, and waivers.',
    category: 'finance',
    is_core: false,
    default_enabled: true,
    icon: 'Receipt',
    permissions_provided: ['finance.fee_structures', 'finance.invoices', 'finance.collect_payment', 'finance.waivers'],
  },
  {
    id: 'mod-student-accounting',
    code: 'student_accounting',
    name: 'Student Accounting & Ledgers',
    description: 'Individual student financial accounts, payment plans, statement of accounts, deposit balances, and refunds.',
    category: 'finance',
    is_core: false,
    default_enabled: true,
    icon: 'CreditCard',
    permissions_provided: ['finance.ledgers', 'finance.refunds'],
  },
  {
    id: 'mod-office-accounting',
    code: 'office_accounting',
    name: 'Income, Expenses & Office Accounting',
    description: 'Institution operational budgets, income vouchers, expense approvals, vendor payables, and financial reporting.',
    category: 'finance',
    is_core: false,
    default_enabled: false,
    icon: 'DollarSign',
    permissions_provided: ['accounting.expenses', 'accounting.income', 'accounting.reports'],
  },

  // Staff & Administration
  {
    id: 'mod-hr',
    code: 'human_resources',
    name: 'Human Resources & Payroll',
    description: 'Staff directory, departments, positions, leave management, staff attendance, contracts, and payroll slips.',
    category: 'administrative',
    is_core: false,
    default_enabled: true,
    icon: 'Users',
    permissions_provided: ['hr.manage', 'hr.payroll', 'hr.leave'],
  },
  {
    id: 'mod-front-office',
    code: 'front_office',
    name: 'Front Office & Reception',
    description: 'Visitor logs, gate passes, phone call logs, incoming/outgoing postal dispatch, and public inquiries.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'Inbox',
    permissions_provided: ['front_office.visitors', 'front_office.dispatch'],
  },
  {
    id: 'mod-library',
    code: 'library',
    name: 'Library Management',
    description: 'Book cataloging (ISBN/Barcode), issue/return tracking, overdue fine calculation, and digital e-book access.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'Library',
    permissions_provided: ['library.catalog', 'library.issue'],
  },
  {
    id: 'mod-inventory',
    code: 'inventory',
    name: 'Inventory & Assets',
    description: 'Asset tracking, school consumables, supplier purchase orders, stock balance warnings, and room inventories.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'Package',
    permissions_provided: ['inventory.manage', 'inventory.audit'],
  },
  {
    id: 'mod-transport',
    code: 'transport',
    name: 'Transport & Fleet',
    description: 'Bus fleet tracking, vehicle maintenance, routes, pickup stops, and student passenger manifests.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'Bus',
    permissions_provided: ['transport.routes', 'transport.manifest'],
  },
  {
    id: 'mod-hostel',
    code: 'hostel',
    name: 'Hostel & Residential Boarding',
    description: 'Dormitory buildings, room and bed allocations, warden assignments, and boarding student status.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'Home',
    permissions_provided: ['hostel.rooms', 'hostel.residents'],
  },

  // Communication & Public Presence
  {
    id: 'mod-communication',
    code: 'communication',
    name: 'Communication, Chat & SMS',
    description: 'Institution-wide notices, SMS/Email broadcasts to parents, direct staff-parent messaging, and push alerts.',
    category: 'communication',
    is_core: false,
    default_enabled: true,
    icon: 'MessageSquare',
    permissions_provided: ['comms.broadcast', 'comms.chat'],
  },
  {
    id: 'mod-events',
    code: 'events_calendar',
    name: 'Events & Institution Calendar',
    description: 'Academic calendar, sports day, parent-teacher conferences, examination windows, and public event feeds.',
    category: 'communication',
    is_core: false,
    default_enabled: true,
    icon: 'Calendar',
    permissions_provided: ['events.manage', 'events.view'],
  },
  {
    id: 'mod-website',
    code: 'institution_website',
    name: 'Institution Website & CMS',
    description: 'Dedicated branded public website builder directly connected to live Admissions, Events, and Staff directories.',
    category: 'communication',
    is_core: false,
    default_enabled: true,
    icon: 'Globe',
    permissions_provided: ['website.publish', 'website.design', 'website.admissions_link'],
  },
  {
    id: 'mod-certificates',
    code: 'certificates_cards',
    name: 'Certificates & Student ID Cards',
    description: 'Template designer for Student ID cards, staff badges, transfer certificates, and graduation diplomas with QR codes.',
    category: 'administrative',
    is_core: false,
    default_enabled: false,
    icon: 'CreditCard',
    permissions_provided: ['certificates.design', 'certificates.issue'],
  },

  // Intelligence
  {
    id: 'mod-ai-intelligence',
    code: 'ai_intelligence',
    name: 'ACADEEMIA AI Intelligence Layer',
    description: 'Tenant-isolated AI queries, predictive student risk analysis, natural language financial reports, and administrative workflows.',
    category: 'intelligence',
    is_core: false,
    default_enabled: true,
    icon: 'Sparkles',
    permissions_provided: ['ai.assistant', 'ai.predictive', 'ai.audit'],
  }
];

export function getModuleByCode(code: string): ModuleDefinition | undefined {
  return SYSTEM_MODULES.find((m) => m.code === code);
}
